name: "data_platform"
version: "1.0.0"
config-version: 2

profile: "crypto_pipeline"

model-paths: ["models"]

models:
  data_platform:
    crypto:
      +materialized: table
      +schema: crypto
    bcentral:
      +materialized: table
      +schema: bcentral